### ISSUE TITLE
Even more strict input validation.

### ISSUE THREAD

**Issue by F483** [Storj/dataserv-client#104]
People are setting invalid arguments like negative set height intervals. Every input argument must be validated.

**Comment by littleskunk** [comment]
At the moment even arguments like retry_delay are wrong validated. They use btctxstore desierialize.positive_integer. 0 ist allowed. Polling with 0 delay? I dont think that is good for the server.

Same problem for height interval 0. That should cause a zero division exception.

I see no argument that needs 0. Maybe change btctxstore to validate greater 0 and use it for the new implemented arguments? Should i open a issue for that?

Anyway that are 2 different Bugs. For now i will implement the missing validations. Later i will check the 0 and report the results.

**Comment by littleskunk** [comment]
Validation for max_size and height interval added + unit test for both.

Confirmed the height intervall 0 bug (0 division exception) and the 0 delay poll. That is still open. Please check if the validation btctxstore positive_interger can be modified.

**Comment by F483** [comment]
Added input validation for all arguments.
