### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by boshevski** [Storj/dataserv-client#114]
In order to get the online farmers JSON http://status.driveshare.org/api/online/json
and the total storage JSON http://status.driveshare.org/api/total
we need to enable CORS on the live.driveshare.org server, or use JSONP.

**Comment by super3** [comment]
@F483 @boshevski Should be on https://github.com/Storj/dataserv

**Comment by F483** [comment]
If I run a local server with `python -m SimpleHTTPServer 8000` from the driveshare.org repo, the status page works just fine. What is the exact problem?

**Comment by F483** [comment]
The info on http://driveshare.org/status.html is also correct. Where is the place with the CORS issue @super3 @boshevski ?

**Comment by F483** [comment]
See http://driveshare.org/status-test.html

**Comment by F483** [comment]
Fixed, see https://github.com/Storj/dataserv/commit/790e1534d5a4049286a354af582f0e0fd1140113
