### ISSUE TITLE
OS X - fails to upgrade from 2.0.3

### ISSUE THREAD

**Issue by JeremyPepper2** [Storj/dataserv-client#115]
Jeremys-MacBook-Pro:~ jeremypepper$ pip3 install dataserv-client --upgrade
Requirement already up-to-date: dataserv-client in ./anaconda/lib/python3.4/site-packages
Requirement already up-to-date: RandomIO==0.2.1 in ./anaconda/lib/python3.4/site-packages (from dataserv-client)
Requirement already up-to-date: partialhash==1.1.0 in ./anaconda/lib/python3.4/site-packages (from dataserv-client)
Requirement already up-to-date: future==0.15.0 in ./anaconda/lib/python3.4/site-packages (from dataserv-client)
Requirement already up-to-date: btctxstore==4.4.0 in ./anaconda/lib/python3.4/site-packages (from dataserv-client)
Requirement already up-to-date: pycrypto>=2.6.1 in ./anaconda/lib/python3.4/site-packages (from RandomIO==0.2.1->dataserv-client)
Requirement already up-to-date: six==1.9.0 in ./anaconda/lib/python3.4/site-packages (from btctxstore==4.4.0->dataserv-client)
Requirement already up-to-date: pycoin==0.52 in ./anaconda/lib/python3.4/site-packages (from btctxstore==4.4.0->dataserv-client)
Requirement already up-to-date: ecdsa==0.13 in ./anaconda/lib/python3.4/site-packages (from btctxstore==4.4.0->dataserv-client)
Jeremys-MacBook-Pro:~ jeremypepper$ dataserv-client version
2.0.3
Jeremys-MacBook-Pro:~ jeremypepper$

**Comment by F483** [comment]
Publish 2.1.2 to pypi
