### ISSUE TITLE
farm command missing parameters

### ISSUE THREAD

**Issue by littleskunk** [Storj/dataserv-client#119]
I would like to use the new farm command and set the height interval to 10000 but it looks like the build parameters are not allowed for farm.

Later i will try:
delay and limit for poll
set_wallet and set_payout for config

There are no unit test for farm.

**Comment by littleskunk** [comment]
@F483 please take a look into the pull request.
Added the params for build and for poll. I did not add the config params.
Unit test added for farm with and without registered befor.

**Comment by F483** [comment]
fixed by @littleskunk
