### ISSUE TITLE
Storage filling is too slow

### ISSUE THREAD

**Issue by sevims** [Storj/dataserv-client#120]
Upon running the farmer, filling up the disks with data takes too much time. It fills at a pace about 1,5TB/day. For a PB storage it would take 2 years to complete. Am I doing something terribly wrong here ? 

ps: dataserv-client (v2.1.2) consumes %100 on a single core only, iowait is not an issue at all.

**Comment by super3** [comment]
Currently we are using the [RandomIO](https://github.com/storj/randomio) library to handle data generation. It currently does not handle multi-threading. We would love to put a bounty on it, and have someone handle that. @mtlynch has most recently working on it. We plan on discarding RandomIO in the future, so we are not keep to add too much support to it, but in the short term it would be nice to be faster.

**Comment by bsom** [comment]
I'm no expert, but this:

import os
with open('output_file', 'wb') as fileout:
    fileout.write(os.urandom(134217728))

Drops a 'random' 128MB file on my disk before I can blink.

**Comment by super3** [comment]
@bsom see RandomIO on how we generate the data.

**Comment by bsom** [comment]
OK, I see that.  You want hex?

import os
import binascii
with open('output_file','wb') as fout:
   fout.write(binascii.hexlify(os.urandom(67108864)))

:-)

**Comment by super3** [comment]
Handling this in #136
