### ISSUE TITLE
V2.1.2 no recognizing drive path NAS

### ISSUE THREAD

**Issue by pthalodezin** [Storj/dataserv-client#121]
Wiindows 10 64bit
Python 2.7.10
NAS = WD EX4 

This was working just fine with 2.0.3 but when I upgraded dataserv-client with python (verified), I get the following error.  Drive is accessible via windows .. Direct IP path also attempted (same response)

c:\Python27>python Scripts/dataserv-client --config_path C:\Users\pthalodezin\.storj\config5.json --store_path X:\FARM5 --max_size 15.8TB --url http://status.driveshare.org:5000 --debug build --set_height_interval 100
Traceback (most recent call last):
  File "Scripts/dataserv-client", line 10, in <module>
    cli.main(sys.argv[1:])
  File "c:\Python27\lib\site-packages\dataserv_client\cli.py", line 165, in main
    config_path=arguments.pop("config_path"),
  File "c:\Python27\lib\site-packages\dataserv_client\api.py", line 61, in __init__
    if control.util.get_fs_type(self.store_path) == "vfat":
  File "c:\Python27\lib\site-packages\dataserv_client\control\util.py", line 51, in get_fs_type
    raise exceptions.PartitionTypeNotFound(path)
dataserv_client.exceptions.PartitionTypeNotFound: Couldn't find partition type for path: 'X:\FARM5'!

**Comment by littleskunk** [comment]
duplicate to https://github.com/Storj/dataserv-client/issues/116
will be fixed in the next version

**Comment by pthalodezin** [comment]
Sorry, I missed that.
