### ISSUE TITLE
Http error

### ISSUE THREAD

**Issue by e39de54f0a157772c11c759dc0d2f531** [Storj/dataserv-client#125]
Hi,
version 1.1.0 works fine for me, but when I updated tot 2.1.2 I got this:

![capture](https://cloud.githubusercontent.com/assets/14231542/9809841/0d565172-586c-11e5-8f39-5e0494d0e775.PNG)

Do you know what this httperror means?

**Comment by littleskunk** [comment]
Please sync your clock with the internet and try again.

**Comment by e39de54f0a157772c11c759dc0d2f531** [comment]
My clock is in sync.

**Comment by littleskunk** [comment]
Please try a better sync server. I did a test with my clock out of sync and i get the same message like you. (It is a bug cause you should get a better message see https://github.com/Storj/dataserv-client/issues/126)

If it still dont work you can try my server. I can see in the logs what time difference you have.

**Comment by e39de54f0a157772c11c759dc0d2f531** [comment]
I set time from automatically to manual, and back to auto. The time has not changed but it is working now, thanks!
![capture](https://cloud.githubusercontent.com/assets/14231542/9836081/8b921df0-5a0b-11e5-99cc-dd6f4918443a.PNG)
