### ISSUE TITLE
Failed building wheel for psutil

### ISSUE THREAD

**Issue by gabesbit** [Storj/dataserv-client#129]
Successfully installed and run Storj dataserv-client on my old Synology box up to version 2.0.3.
Version 2.1.2 failed to upgrade. Here is the log file: http://pastebin.com/ea8JEPc9
Any suggestion? Thanks!

**Comment by F483** [comment]
Did you install the python header files? 

On debian/ubuntu `sudo apt-get install python3-dev`

**Comment by littleskunk** [comment]
+
did you install gcc?

**Comment by gabesbit** [comment]
It have python 3.4.1 installed via https://synocommunity.com/packages. But it is an ARM machine and it seems no debian environment nor gcc for me. Therefore can't install python-dev. 2.0.3 was runing just fine. Will the python-dev package be always required for the future versions?

**Comment by littleskunk** [comment]
I have a QNAP NAS with ARM CPU as well. Use ipkg to install gcc and python-dev.

**Comment by gabesbit** [comment]
I have no luck. ipkg list for my NAS doesn't include gcc and python-dev. http://ipkg.nslu2-linux.org/feeds/optware/ds101g/cross/unstable/ Maybe when https://synocommunity.com/packages will update to python 3.5 I'll try again. Thanks for suggestions.

**Comment by super3** [comment]
@gabesbit Aww man that sucks. Based on what I remember and from the changelog you should be able to run 2.0.3 on the current network, although you won't have access the farm command. 

After we add uptime and audits you might come back around. After that we should not be adding any new dependencies for a while, and it might be worth trying to figure out a work around.

GCC and python-dev are pretty major packages. Might worth asking the Syno community to add them to available package?
