### ISSUE TITLE
Handle Multi-Process Building in RandomIO - 10K SJCX Bounty

### ISSUE THREAD

**Issue by super3** [Storj/dataserv-client#136]
Currently RandomIO takes a single seed, and generates the data with a single process. This will max out a single core, but really doesn't touch IO. Instead we want to send in multiple seeds to RandomIO as well as the number of cores we would like to use. This should speed up building significantly.

**Comment by agrimaldi** [comment]
Does it have to be python 2 and 3 compatible? If yes, does it make sense? Going for python3 only would ease things quite a bit I think.

**Comment by super3** [comment]
Yes we test on Python 2.7, 3.3, and 3.4

**Comment by littleskunk** [comment]
My pull request is running on the 3 python versions. Unit test passed. At the moment it is running with 8 threads. It is easy to change that number.

**Comment by littleskunk** [comment]
@super3 
I gues a addition argument for build and farm would be nice. What name do you like? --core, --threads --threadcount?

**Comment by johnavgeros** [comment]
If you asked me, --core sounds more familiar, I just don't know if I count as the average people...

**Comment by littleskunk** [comment]
Added --workers for build and farm, validation for positiv int and unit tests. Local unit tests passed.

**Comment by sevims** [comment]
Any updates on this issue? We do have some massive storage space to try this out but holding on due to slow building. @super3

**Comment by super3** [comment]
It's been implemented and will be in the next release.
