### ISSUE TITLE
Add HTTP Error Codes to Log

### ISSUE THREAD

**Issue by super3** [Storj/dataserv-client#144]
Just shows the line number. Should also pass the error codes.

**Comment by littleskunk** [comment]
Which error codes do you mean?

Server error codes all all catch and loged in a way the user can read them. I removed the duplicate logmessages but if you like i can add the again. 
Missing error codes like 413 will hit the raise statement.
https://github.com/Storj/dataserv-client/blob/develop/dataserv_client/messaging.py#L47

HTTPExceptions, URLError, socket.error will be catched as well but without stacktrace. Would you like to see the full exception message? All of them or only HTTPExceptions?
https://github.com/Storj/dataserv-client/blob/develop/dataserv_client/messaging.py#L63

**Comment by littleskunk** [comment]
one part is fiexed with https://github.com/Storj/dataserv-client/commit/8086d3abaa251d26d6233ed9422f0c2f1b590d93

error codes are still missing. I will add them now.

**Comment by littleskunk** [comment]
error codes fixed as well https://github.com/Storj/dataserv-client/commit/ebfe4ca2b425aa10a6b5de84857b21b915bd43c0
