### ISSUE TITLE
Bug at build

### ISSUE THREAD

**Issue by alphaonex86** [Storj/dataserv-client#15]
python2.7 dataserv-client --address=15Rs7YLUP4NdZF37a4GEsiCxEwnAKHWeUd --max_size=1600149724 --store_path=/home/dataserv-client-master/dataserv_client/bin/data/ build
Failed. Only 11 files is created. replace = space and do max_size multiple of 128*1024*1024 work

Can you ceil the max_size or do a warning.
Or fix this. Thanks

**Comment by super3** [comment]
Bit confused on your issue. 1600149724 bytes = 1.6 GB so 11 files should be generated(128 MB each). Please be a little more descriptive.

**Comment by alphaonex86** [comment]
Not do 11.92204448580742 and will be 12 files? I think I was tired, I close this issue and come back after some test.
