### ISSUE TITLE
https://github.com/Storj/dataserv-client/blob/v2.1.4/dataserv_client/common.py wrong

### ISSUE THREAD

**Issue by alphaonex86** [Storj/dataserv-client#165]
Hello,

https://github.com/Storj/dataserv-client/blob/v2.1.4/dataserv_client/common.py
DEFAULT_URL = "http://status.driveshare.org" is wrong, should be switch.driveshare.org

Cheers,

**Comment by littleskunk** [comment]
http://ping.eu/nslookup/

status.driveshare.org = 104.236.1.59
switch.driveshare.org = 104.236.1.59

Both DNS entries are pointing to the same server. Closed as user error.
