### ISSUE TITLE
Is dataserv-client all I need?

### ISSUE THREAD

**Issue by NginUS** [Storj/dataserv-client#168]
Hi,

I have dataserv-client running headless on an Ubuntu server, with it set to share 777GB. I'd like to know if I need to run the Driveshare-GUI to share my disk & farm. Or if it's already farming due to dataserv-client running.

Yesterday I tried installing Driveshare-GUI to a KDE frontend, & I got it running, but it would totally freeze the VM at boot such that the desktop wouldn't even load, so I had to revert back to headless. Something else to note is that it would report that I only had ~500GB available to allocate to farming, & I wonder if that's because of the space dataserv-client was using at the time.

I hope I can get away with just running dataserv-client, as it's what is stable & running with no problem already.

Please advise.

Thanks,
-N

EDIT:
Upon further investigation I see now that the headless VM I have running dataserv-client is still freezing & I'm unable to logon via ssh.

I've destroyed the VM & will try installing the client directly on Windows 10.

**Comment by littleskunk** [comment]
Please open issues for Driveshare-GUI if you found some bugs. https://github.com/Storj/driveshare-gui/issues

You can use dataserv-client without Driveshare-GUI. If you have more questions you can ask in channel #test_group_b http://slack.storj.io/
