### ISSUE TITLE
Address/Space not appearing on 'Status' page

### ISSUE THREAD

**Issue by NginUS** [Storj/dataserv-client#169]
I have dataserv-client running & appears to be successfully sharing 777GB on the network, but it doesn't appear on the list at: http://driveshare.org/status.html

Do I just have to wait for it or something? How can I verify it's working properly if it doesn't show up there?

**Comment by littleskunk** [comment]
The full details you can see here: http://status.driveshare.org/api/online/json

If your payout address is missing please take a look into the FAQ (http://storj.io/faq.html). If you have more questions you can ask in channel #test_group_b http://slack.storj.io/
