### ISSUE TITLE
Dataserv-client randomly freezing

### ISSUE THREAD

**Issue by CurreE** [Storj/dataserv-client#172]
Sometimes my dataserv-client will freeze, causing me to drop off the stats page.  This is with version 2.1.4, running 24/7 on my Windows 8 64-bit desktop PC.  When this happens it doesn't crash, it simply freezes and stops displaying output.  The text display will have the usual query timestamp and then nothing after that, so there is no indication of what went wrong.  It happens at random times, usually 2-3 times per week.

**Comment by littleskunk** [comment]
If it happens again please hit enter on your keyboad.
If that works something on your dektop pc paused the prozess. Maybe somebody pressed the pause button on your keyboard? Some keyboards will send that command with Ctrl + Num as well. I gues there are some more combinations and keyboard codes with the same result.

**Comment by littleskunk** [comment]
This bug is 22 days old now. Closed because not reproducible.
