### ISSUE TITLE
tests.test_client.TestClientBuild.test_build_min_free_space is unreliable

### ISSUE THREAD

**Issue by F483** [Storj/dataserv-client#174]
Sometimes the test passes sometimes it doesn't...

The three tests below are all for the same commit (develop, master and tag). To passed and one failed. Whatever part is unreliable needs to be found and fixed.

OK https://travis-ci.org/Storj/dataserv-client/builds/92306748
FAIL https://travis-ci.org/Storj/dataserv-client/builds/92306822
OK https://travis-ci.org/Storj/dataserv-client/builds/92306844

**Comment by super3** [comment]
@littleskunk @F483 Are we doing anything about this issue?

**Comment by F483** [comment]
No it will not be relevant for storjnode.
