### ISSUE TITLE
Handling Of Bad Blocks On Drive

### ISSUE THREAD

**Issue by vindicatorr** [Storj/dataserv-client#175]
I encountered some bad blocks on my drive. I copied off most of my data, but some Bitcoin and Storj had some data files that were affected.
After reformatting the drive while also running "badblocks", I copied everything back over.

With the missing data files, Bitcoin said:
```
Error opening block database
Do you want to rebuild the block database now?
```
It looks like bitcoin's protocol is to rebuild from scratch at any sign of any data issue, rather than just fix the segment(s) that went bad.

Storj didn't say anything to me about any problems and continued from the "current height".
Just making sure such an issue is taken into consideration.

**Comment by super3** [comment]
We won't be checking things like this until the next version of dataserv-client we have implemented audits. We will add some top level checks later on.
