### ISSUE TITLE
Unsatisfied dependency [storjnode>=0.0.11]

### ISSUE THREAD

**Issue by gordonwritescode** [Storj/dataserv-client#176]
Attempting to install `dataserv-client` yields error due to unsatified dependency on `storjnode>=0.0.11`.

```
╭─gordon@gordonhall  ~/Code/driveshare-gui  ‹master*› 
╰─$ sudo -S pip3 install dataserv-client                                                                                                                                                                                                 130 ↵
Downloading/unpacking dataserv-client
  Downloading dataserv_client-2.1.8-py2.py3-none-any.whl
Downloading/unpacking RandomIO>=0.2.1 (from dataserv-client)
  Downloading RandomIO-0.2.1.tar.gz
  Running setup.py (path:/tmp/pip-build-k3dquzz9/RandomIO/setup.py) egg_info for package RandomIO
    
Downloading/unpacking storjcore>=0.0.6 (from dataserv-client)
  Downloading storjcore-0.0.6-py2.py3-none-any.whl
Downloading/unpacking partialhash>=1.1.0 (from dataserv-client)
  Downloading partialhash-1.1.2.tar.gz
  Running setup.py (path:/tmp/pip-build-k3dquzz9/partialhash/setup.py) egg_info for package partialhash
    
Downloading/unpacking future>=0.15.0 (from dataserv-client)
  Downloading future-0.15.2.tar.gz (1.6MB): 1.6MB downloaded
  Running setup.py (path:/tmp/pip-build-k3dquzz9/future/setup.py) egg_info for package future
    
    warning: no files found matching '*.au' under directory 'tests'
    warning: no files found matching '*.gif' under directory 'tests'
    warning: no files found matching '*.txt' under directory 'tests'
Downloading/unpacking btctxstore>=4.6.0 (from dataserv-client)
  Downloading btctxstore-4.6.0.tar.gz
  Running setup.py (path:/tmp/pip-build-k3dquzz9/btctxstore/setup.py) egg_info for package btctxstore
    
Downloading/unpacking storjnode>=0.0.11 (from dataserv-client)
  Could not find a version that satisfies the requirement storjnode>=0.0.11 (from dataserv-client) (from versions: 0.0.3, 0.0.1, 0.0.2)
Cleaning up...
No distributions matching the version for storjnode>=0.0.11 (from dataserv-client)
Storing debug log for failure in /root/.pip/pip.log

```

**Comment by gordonwritescode** [comment]
Assuming a storjnode release needs to be made for 0.0.11?

**Comment by gordonwritescode** [comment]
Actually looks like we are referencing 0.0.18 (https://github.com/Storj/dataserv-client/blob/master/requirements.txt#L7), maybe the dataserv-client is what needs an updated release.

**Comment by littleskunk** [comment]
Python3 (pip3) is not supported at the moment. Please use python2 while we wait for python3 support.

**Comment by JeremyPepper2** [comment]
Same issue here.  Error looks like this:

Collecting storjnode>=0.0.11 (from dataserv-client)
  Could not find a version that satisfies the requirement storjnode>=0.0.11 (from dataserv-client) (from versions: 0.0.1, 0.0.2, 0.0.3)
No matching distribution found for storjnode>=0.0.11 (from dataserv-client)
Jeremys-MacBook-Pro:~ jeremypepper$

**Comment by littleskunk** [comment]
Python3 (pip3) is not supported at the moment. Please use python2 while we wait for python3 support.

**Comment by JeremyPepper2** [comment]
I've used pip and pip3, same error.  Is pip not Python 2?

**Comment by JeremyPepper2** [comment]
Jeremys-MacBook-Pro:~ jeremypepper$ pip install dataserv-client --upgrade
Collecting dataserv-client
  Using cached dataserv_client-2.1.8-py2.py3-none-any.whl
Collecting partialhash>=1.1.0 (from dataserv-client)
  Using cached partialhash-1.1.2.tar.gz
Collecting btctxstore>=4.6.0 (from dataserv-client)
  Using cached btctxstore-4.6.0.tar.gz
Collecting psutil>=3.2.2 (from dataserv-client)
  Using cached psutil-3.3.0.tar.gz
Collecting storjnode>=0.0.11 (from dataserv-client)
  Could not find a version that satisfies the requirement storjnode>=0.0.11 (from dataserv-client) (from versions: 0.0.1, 0.0.2, 0.0.3)
No matching distribution found for storjnode>=0.0.11 (from dataserv-client)
Jeremys-MacBook-Pro:~ jeremypepper$ pip3 install dataserv-client --upgrade
Collecting dataserv-client
  Using cached dataserv_client-2.1.8-py2.py3-none-any.whl
Collecting psutil>=3.2.2 (from dataserv-client)
  Using cached psutil-3.3.0.tar.gz
Collecting storjcore>=0.0.6 (from dataserv-client)
  Using cached storjcore-0.0.6-py2.py3-none-any.whl
Collecting partialhash>=1.1.0 (from dataserv-client)
  Using cached partialhash-1.1.2.tar.gz
Collecting future>=0.15.0 (from dataserv-client)
  Using cached future-0.15.2.tar.gz
Collecting btctxstore>=4.6.0 (from dataserv-client)
  Using cached btctxstore-4.6.0.tar.gz
Requirement already up-to-date: RandomIO>=0.2.1 in ./anaconda/lib/python3.4/site-packages (from dataserv-client)
Collecting storjnode>=0.0.11 (from dataserv-client)
  Could not find a version that satisfies the requirement storjnode>=0.0.11 (from dataserv-client) (from versions: 0.0.1, 0.0.2, 0.0.3)
No matching distribution found for storjnode>=0.0.11 (from dataserv-client)

**Comment by littleskunk** [comment]
You can read it yourself:
Requirement already up-to-date: RandomIO>=0.2.1 in ./anaconda/lib/python3.4/site-packages (from dataserv-client)

You are using python3.4. You can check it with pip --version
