### ISSUE TITLE
Fix logging for windows client.

### ISSUE THREAD

**Issue by F483** [Storj/dataserv-client#181]
Update storjnode dependeencie and ensure logging is sane so that the windows client can be built.

@littleskunk can you add an exact decsription of the problem.

**Comment by littleskunk** [comment]
Here is what i did on my linux nas (debian):
git clone https://github.com/Storj/storjnode.git -b develop
cd storjnode
pip uninstall storjnode
python setup.py install
dataserv-client ping and dataserv-client --debug ping will print out nothing. I dont see any log information.
dataserv-client farm is logging only storjnode information.

**Comment by F483** [comment]
Ok looking into that right now

**Comment by F483** [comment]
Fixed as of https://github.com/Storj/storjnode/commit/b314b9e0f1f317e86644f23918fbb9dc8b38aaaf
