### ISSUE TITLE
Hang - stopped pinging

### ISSUE THREAD

**Issue by nelsonpk** [Storj/dataserv-client#183]
Running non-GUI 2.1.4 on Win 8.1 to an 8TB share on a QNAP NAS, pinging stopped yesterday with no error message - had been running 7.5 days. All other processes still running fine. Closed cmd window and restarted farm OK - no clues in event viewer on local machine.The payout address was 15qNBRy6RC176tuxC6kaWUBWdKTysJpQyc.It stopped about 21 hours ago now, It was running with the --debug option, but nothing showed up in the command window, so the executable would need to be more verbose if we want to catch this one.

**Comment by nelsonpk** [comment]
OK - just happened again - see attached - looks as though it didn't recover fully from the 401
![image](https://cloud.githubusercontent.com/assets/16044038/11653416/01b96128-9d96-11e5-8a3e-7bd9230035eb.png)

**Comment by littleskunk** [comment]
Duplicate https://github.com/Storj/dataserv-client/issues/155

The bug will be fixed in the next version. At the moment we have problems with the logging and cant release a new binary. As workaround you could install python2 for windows.
