### ISSUE TITLE
Did not received reply...

### ISSUE THREAD

**Issue by sammy007** [Storj/dataserv-client#184]
CRITICAL twisted 154: 'Did not received reply for msg id .... within 5 seconds'

I see a lot of these messages, is it such a critical? Once a minute. Possible fix?

**Comment by littleskunk** [comment]
Fixed with the next storjnode version (current 0.0.18). https://github.com/Storj/storjnode/issues/15

**Comment by sammy007** [comment]
I am on latest. Should I bother?

**Comment by sammy007** [comment]
Ah ok, got it.
