### ISSUE TITLE
Implement free space command

### ISSUE THREAD

**Issue by super3** [Storj/dataserv-client#186]
For [driveshare-gui](http://github.com/storj/driveshare-gui) there are some dependency issues with retrieving free disk space in Javascript. What would be better is a command in dataserv-client where you could get the free space available for a certain drive. Example:

    > dataserv-client.exe freespace C:\
    > 4564182 bytes

**Comment by littleskunk** [comment]
Implemented 34fe86b6b8d073466229aad1f7a6a04b094b4b35
I will add some unit tests later.

**Comment by littleskunk** [comment]
Unit test implemented 5cd8a439e478c6b106a2541b302febe6ec567957
