### ISSUE TITLE
Debian package using dh-virtualenv

### ISSUE THREAD

**Issue by gordonwritescode** [Storj/dataserv-client#187]
Right now DriveShare's Debian package uses some conventions that prevent it from being accepted into the Debian archive. Namely, this involves installing `dataserv-client` via `pip` as a `postinst` hook.

If `dataserv-client` could be packaged using [dh-virtualenv](https://github.com/spotify/dh-virtualenv), it could be packaged appropriately for the Debian archive and thus DriveShare could remove the need to perform the aforementioned steps.

This would allow for both DataServ and DriveShare to be published to the Debian archive and would enable installation on Debian based distros via: 

```
apt-get install driveshare
```

and/or 

```
apt-get install dataserv-client
```

**Comment by super3** [comment]
@gordonwritescode Update to this issue?

**Comment by super3** [comment]
Moved to https://github.com/Storj/storjnode/issues/99
