### ISSUE TITLE
Sanity checking for stored values

### ISSUE THREAD

**Issue by subwolf** [Storj/dataserv-client#188]
I've seen thousands of hits from a single IP requesting to store a value, what this is or why I don't know. Is someone trying to send bad data to clients, or see if they can break them?

Log showing value store crush: http://arthur.sdo-srv.com/ds-ouch.log

**Comment by subwolf** [comment]
Had first occasion of a client appearing to crash, in that it froze in the middle of listing peers, don't know exact point because a malicious peer sent bad data that messed up the display again.

**Comment by subwolf** [comment]
See http://pastebin.com/raw/p5txjnWe - got stuck in the middle of an INFO statement, discovered at 22:15, 45 minutes later, the client was likely down during that period and losing uptime. Didn't think to query the driveshare status list, will do next time. If this happens and I'm away for several hours this will be a big problem.

You say use StorjWatch? Unreliable at this time, get false positives a few times daily.

**Comment by super3** [comment]
@subwolf Organizing the bugs. This is valid but belongs in https://github.com/Storj/storjnode. Please reopen there.
