### ISSUE TITLE
Filesystem type detection

### ISSUE THREAD

**Issue by MrFancyMonocle** [Storj/dataserv-client#189]
Opening this issue to discuss filesystem detection 
In reference to https://github.com/Storj/driveshare-gui/issues/57 for dataserv-gui
In the Dataserv-client cli -help, I'm seeing
```
--use_folder_tree     Use folder tree to store files (always on for fat32 store_path).
```
I'm not certain that the GUI should be passing the use_folder_tree option here; to me, it seems like the dataserv-client should be determining the file system type to eliminate the need for client applications to implement various cross-platform file system detection or worse, a checkbox for a user to tell a machine about itself. I wanted to gather thoughts concerning this addition, thanks.

**Comment by gordonwritescode** [comment]
Storjnode implements this in utils: https://github.com/Storj/storjnode/blob/master/storjnode/util.py

Cake.

**Comment by littleskunk** [comment]
The fat32 detection moves from dataserv-client to storjnode. https://github.com/Storj/dataserv-client/blob/master/dataserv_client/api.py#L66

At the moment we can't detect fat32 drives for sure. One of the problems is: https://code.google.com/p/psutil/issues/detail?id=434

**Comment by super3** [comment]
From what I understand this is already implemented, just detection remains spotty.
