### ISSUE TITLE
HTTP Error 401: UNAUTHORIZED on command line dataserv-client v2.1.12

### ISSUE THREAD

**Issue by heunland** [Storj/dataserv-client#190]
I started getting intermittant 401 Error while farming on command line dataserv-client v2.1.4 despite having  just synched my clock. Upgraded to v2.1.12 and still get same error. This is happening on my laptop build with internal drive. My other PC build with external FAT32 drive is still running v 2.1.4 apparently without running into this issue. Below is the log from my laptop build running v2.1.12:

C:\Storj\dataserv-client>dataserv-client --store_path C:\Storj\data --max_size=4
50GB  --use_folder_tree farm
INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/addre
ss
INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/regis
ter/17X82asErw2xt2uNKfrn46nfDgV8G6vVjs/1DcpZCAHN3eYyYSfebftUqwQ5YjnWsHnib
INFO dataserv_client.api 175: Starting build
INFO dataserv_client.builder 108: Resuming from height 3352
INFO dataserv_client.builder 131: Saving seed d39f00ebac7ad061679a7ce5273ec2d3eb
9c25a2869215e8044e64d284036beb with SHA-256 hash e56da40f6e33bf6b072ec89c12f643e
175bad033cb843eb4474618513c8da11d.
INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/heigh
t/17X82asErw2xt2uNKfrn46nfDgV8G6vVjs/3352
INFO dataserv_client.api 190: Current height at 3352.
INFO dataserv_client.api 200: Build finished
INFO dataserv_client.api 135: Pinging server 'http://status.driveshare.org' at 2
015-12-16 15:33:35.
INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/ping/
17X82asErw2xt2uNKfrn46nfDgV8G6vVjs
INFO dataserv_client.api 135: Pinging server 'http://status.driveshare.org' at 2
015-12-16 15:34:55.
INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/ping/
17X82asErw2xt2uNKfrn46nfDgV8G6vVjs
WARNING dataserv_client.messaging 57: HTTP Error 401: UNAUTHORIZED
INFO dataserv_client.messaging 78: Query retry in 30 seconds.
INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/ping/
17X82asErw2xt2uNKfrn46nfDgV8G6vVjs
INFO dataserv_client.api 135: Pinging server 'http://status.driveshare.org' at 2
015-12-16 15:37:07.
INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/ping/
17X82asErw2xt2uNKfrn46nfDgV8G6vVjs
WARNING dataserv_client.messaging 57: HTTP Error 401: UNAUTHORIZED
INFO dataserv_client.messaging 78: Query retry in 30 seconds.
INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/ping/
17X82asErw2xt2uNKfrn46nfDgV8G6vVjs
WARNING dataserv_client.messaging 57: HTTP Error 401: UNAUTHORIZED
INFO dataserv_client.messaging 78: Query retry in 30 seconds.
INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/ping/
17X82asErw2xt2uNKfrn46nfDgV8G6vVjs
INFO dataserv_client.api 135: Pinging server 'http://status.driveshare.org' at 2
015-12-16 15:40:25.
INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/ping/
17X82asErw2xt2uNKfrn46nfDgV8G6vVjs
WARNING dataserv_client.messaging 67: URLError(TimeoutError(10060, 'A connection
 attempt failed because the connected party did not properly respond after a per
iod of time, or established connection failed because connected host has failed
to respond', None, 10060, None),)
INFO dataserv_client.messaging 78: Query retry in 30 seconds.
INFO dataserv_client.messaging 43: Query: http://status.driveshare.org/api/ping/
17X82asErw2xt2uNKfrn46nfDgV8G6vVjs

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/dataserv-client/issues/178

The final fix comes with https://github.com/F483/btctxstore/issues/12. As workaround the next dataserv (server) version has a higher timeout. We are still using the old server version.
