### ISSUE TITLE
Does not run on FreeBSD due to pyroute2.

### ISSUE THREAD

**Issue by F483** [Storj/dataserv-client#193]
> just popping in to report I can't run dataserv-client on FreeBSD due to linux-only support in pyroute2
> specifically, pyroute2 tries to access /proc/net/psched which doesn't exist on FreeBSD
> - catbref

```
File "/usr/local/lib/python2.7/site-packages/pyroute2/netlink/rtnl/tcmsg.py", line 29, in <module>
   _psched = open('/proc/net/psched', 'r')
IOError: [Errno 2] No such file or directory: '/proc/net/psched'
```

**Comment by littleskunk** [comment]
Duplicate?
https://github.com/Storj/pyp2p/issues/16

**Comment by F483** [comment]
Not a duplicate but closely related. This is FreeBSD and not OSX, though OSX is based on FreeBSD and differs not to much.
