### ISSUE TITLE
Can't upgrade dataserv-client on FreeBSD

### ISSUE THREAD

**Issue by corv89** [Storj/dataserv-client#195]
sudo pip install dataserv-client --upgrade fails with:

    Collecting storjnode>=0.0.11 (from dataserv-client)
    Could not find a version that satisfies the requirement storjnode>=0.0.11 (from dataserv-client) (from versions: 0.0.1, 0.0.2, 0.0.3)
    No matching distribution found for storjnode>=0.0.11 (from dataserv-client)```

I've got storjnode 0.0.3 installed and can't upgrade further.

**Comment by littleskunk** [comment]
dataserv-client don't support python3 at the moment. Follow the install introduction: https://github.com/Storj/dataserv-client/blob/master/README.rst#linux-ubuntumintdebian

**Comment by corv89** [comment]
Thanks, didn't realize that. The newly introduced graphviz dependency is nuts on a headless box...

**Comment by littleskunk** [comment]
graphviz will be removed with the next storjnode version. You can install the storjnode develop branch but i don't know how stable the develop branch is. Better wait for the next storjnode release.

**Comment by corv89** [comment]
Oh alright, thanks!
