### ISSUE TITLE
Data collection for uptime tracking not working

### ISSUE THREAD

**Issue by subwolf** [Storj/dataserv-client#196]
See http://graph.driveshare.org/api/summary/15tEiA7mTmEeY7APUfmpYwvsWdSBuDghfh which is for one of my payment addresses. Corroborated by @jaylagorio and a concern, as without this data there is no way to collect uptime statistics for payout.

**Comment by super3** [comment]
Appears to be working now. Can you verify?

**Comment by super3** [comment]
Appears to be working now. Can you verify @subwolf?

**Comment by subwolf** [comment]
Have to wait for 24 hours to see if it updates.

**Comment by jaylagorio** [comment]
Does the stat for the previous day get recorded at midnight? If so, midnight in what timezone? I'll keep an eye on the above link and one of mine (http://graph.driveshare.org/api/summary/16uM37KNrDmgCC2BYC5Z45rZ43XMEWTY25) to see if I get a new data point in the morning.

**Comment by subwolf** [comment]
No change here so far.

**Comment by jaylagorio** [comment]
Same, no new data.

**Comment by subwolf** [comment]
I'm seeing older entries dropping off the end, but no new data appearing at the front.

**Comment by subwolf** [comment]
**confirmed** see http://pastebin.com/eeuzANft ran one yesterday, one today.

**Comment by jaylagorio** [comment]
Yeah, I'm sure old entries dropping off is by design but we need new data to do any meaningful tracking. I guess the uptime graph I just added to StorjTrackr wasn't timed very well.

**Comment by super3** [comment]
Yeah the summary API is clearly not working properly. All the other data including the internal graphs are working correctly. Looking into this.

**Comment by super3** [comment]
Moved to https://github.com/Storj/driveshare-graph/issues/2
