### ISSUE TITLE
Only using a single CPU thread to fill storage

### ISSUE THREAD

**Issue by bathrobehero** [Storj/dataserv-client#199]
It would be nice to have an option to use multiple CPU cores to fill the initial storage directory because as it stands it's really slow and is only using 1 CPU thread in Windows (or 25% of a quad core CPU).

**Comment by subwolf** [comment]
You can use the --workers option to use more CPU power. I use four for my PC.

**Comment by bathrobehero** [comment]
Oh, nice. the --help doesn't include the --workers argument. I guess now I can use the dataserv-client to fill the storage faster with --workers 4 and switch back to the GUI client.

**Comment by littleskunk** [comment]
https://github.com/Storj/dataserv-client/blob/master/README.rst#workers-guide

Check out the help information for build and farm command. --worker is an argument for both commands.
```dataserv-client build --help
dataserv-client farm --help```

**Comment by bathrobehero** [comment]
I see, thanks. Unfortunately I always got 10061 - connection refused even if I specify the port so I'm sticking with the GUI because that's slowly, but working.

**Comment by littleskunk** [comment]
https://github.com/Storj/driveshare-gui/issues/175

**Comment by bathrobehero** [comment]
Solved it. Now with 3 workers on a 3570K I run into I/O bottleneck on raid0 HDDs.
