### ISSUE TITLE
Pip3, not pip

### ISSUE THREAD

**Issue by unsystemizer** [Storj/dataserv-client#2]
Shouldn't this be pip3 (readme.rst): 

Download and install Python 3.4 TODO add pycrypto instructions
$ pip install dataserv-client
$ dataserv-client.py version

**Comment by F483** [comment]
Yes you are correct. I fixed it for the linux setup. For windows pleas use the compiled bundle https://storjcommunity.slack.com/files/fabe/F08PHKQUU/dataserv-client_1.0.8_windows.zip

I will update the windows setup in the readme for the next build.
