### ISSUE TITLE
Saving seed xyz with SHA-256 hash None.

### ISSUE THREAD

**Issue by ELQET** [Storj/dataserv-client#200]
![debian_dataserv_client_doesnt_work](https://cloud.githubusercontent.com/assets/6269862/12642603/24ac2b40-c5b7-11e5-9357-6a16c6161ccc.png)

On Debian Jessie (without GUI) system I have problem with dataserv-client.I have done everything from your instruction from here (Linux tab) http://driveshare.org/dataserv.html but dataserv-client has strange behaviour. I have registered address with 
dataserv-client config --set_payout_address="MY ADDRESS"
and after that I run command 
dataserv-client --store_path="mypath" --max_size="mysizeinbytes" farm
and it starts building but in the very strange way.
Because output messages is like this: **Saving seed xyz with SHA-256 hash None.**
And this None is my concern. My hard-drive is mounted in read/write mode and everybody has access right to it. I have tested it. So I don't know why it doesn't work normally. In Ubuntu I have no problem (it works ok) with this but only in my debian jessie system. 
I thought that it is new feature of the newest version but after I have  left it all night building, still no record about sharing size in this online list here http://driveshare.org/status.html
So I decided first to ask in group test B in slack but nobody answered so far. And here maybe somebody could help me with this issue. Screenshot is from terminal from which I connect via SSH to debian system on other PC and height is low because I have restarted and deleted whole share directory and started once again but it didn't help. Thank you in advance for some help I hope it is not bug, maybe some dependencies missing but I don't know which.

**Comment by subwolf** [comment]
Mine does that but it works just fine.

**Comment by littleskunk** [comment]
Old unused code. We added multi threading some time ago. The files on your drive are fine. Only the log entry is buged. You can ignore that.
