### ISSUE TITLE
storjnode>=0.0.11requirement not found

### ISSUE THREAD

**Issue by MatteoCarotta** [Storj/dataserv-client#205]
I'm tring to install the dataserv-client on a new pc on Ubuntu 15.10 and I'm experiencing some issues.

First of all to run properly `sudo pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"`
I had to run: `easy_install pip`

But when i run: `sudo pip install dataserv-client` i get:
```
Downloading/unpacking dataserv-client
  Downloading dataserv_client-2.1.8-py2.py3-none-any.whl
Downloading/unpacking storjcore>=0.0.6 (from dataserv-client)
  Downloading storjcore-0.0.6-py2.py3-none-any.whl
Downloading/unpacking partialhash>=1.1.0 (from dataserv-client)
  Downloading partialhash-1.1.3.tar.gz
  Running setup.py (path:/tmp/pip-build-jeew8ws2/partialhash/setup.py) egg_info for package partialhash
    Downloading/unpacking psutil>=3.2.2 (from dataserv-client)
  Downloading psutil-4.0.0.tar.gz (293kB): 293kB downloaded
  Running setup.py (path:/tmp/pip-build-jeew8ws2/psutil/setup.py) egg_info for package psutil
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no files found matching '*.rst' under directory 'scripts'
    warning: no files found matching '*README' under directory 'scripts'
Requirement already satisfied (use --upgrade to upgrade): btctxstore>=4.6.0 in ./.local/lib/python3.4/site-packages (from dataserv-client)
Downloading/unpacking RandomIO>=0.2.1 (from dataserv-client)
  Downloading RandomIO-0.2.1.tar.gz
  Running setup.py (path:/tmp/pip-build-jeew8ws2/RandomIO/setup.py) egg_info for package RandomIO 
Requirement already satisfied (use --upgrade to upgrade): future>=0.15.0 in ./.local/lib/python3.4/site-packages (from dataserv-client)
Downloading/unpacking storjnode>=0.0.11 (from dataserv-client)
  Could not find a version that satisfies the requirement storjnode>=0.0.11 (from dataserv-client) (from versions: 0.0.3, 0.0.1, 0.0.2)
Cleaning up...
No distributions matching the version for storjnode>=0.0.11 (from dataserv-client)
Storing debug log for failure in /home/mat650/.pip/pip.log
```

**Comment by littleskunk** [comment]
Duplicate: https://github.com/Storj/dataserv-client/issues/176

Pygraphviz is not needed anymore. Better use this guide: https://github.com/Storj/dataserv-client/blob/develop/README.rst#linux-ubuntumintdebian

**Comment by MatteoCarotta** [comment]
It doesn't works, I get:
`mat650@NodeITC1:~$ dataserv-client`
`Traceback (most recent call last):
  File "/usr/local/bin/dataserv-client", line 6, in <module>
    from dataserv_client import cli
  File "/usr/local/lib/python2.7/dist-packages/dataserv_client/cli.py", line 4, in <module>
    from dataserv_client import api
  File "/usr/local/lib/python2.7/dist-packages/dataserv_client/api.py", line 7, in <module>
    import storjnode
  File "/usr/local/lib/python2.7/dist-packages/storjnode/__init__.py", line 3, in <module>
    from . import network  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/storjnode/network/__init__.py", line 1, in <module>
    from . import node  # NOQA
  File "/usr/local/lib/python2.7/dist-packages/storjnode/network/node.py", line 19, in <module>
    from storjnode.network.file_transfer import FileTransfer
  File "/usr/local/lib/python2.7/dist-packages/storjnode/network/file_transfer.py", line 4, in <module>
    import pyp2p.dht_msg
  File "/usr/local/lib/python2.7/dist-packages/pyp2p/dht_msg.py", line 10, in <module>
    from storjkademlia.node import Node as KadNode
ImportError: No module named storjkademlia.node
`
Than I tried: 
`mat650@NodeITC1:~$ pip install storjkademlia`
I got: `Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead`

So... I did: 
1.`sudo apt-get remove python-pip`
2.`sudo easy_install -U pip`
3.`sudo pip install --upgrade virtualenv`
4.`sudo pip install dataserv-client`
5. `sudo pip install storjkademlia`

And now I get:
`mat650@NodeITC1:~$ dataserv-client version
2.1.12`

So... maybe the Setup procedure need to be reviewed !?

**Comment by littleskunk** [comment]
First problem was that: https://github.com/Storj/driveshare-gui/issues/182
The reason for the second one is a old pip version. I will add `pip install pip --upgrade` to storjnode readme.

**Comment by MatteoCarotta** [comment]
Thanks ;)

**Comment by littleskunk** [comment]
https://github.com/Storj/storjnode/commit/0ff6b5385131a6f96c8bcea61c807e955bbeebd7
