### ISSUE TITLE
Unable to install dataserv-client with pip

### ISSUE THREAD

**Issue by IgorGanapolsky** [Storj/dataserv-client#208]
I am running `python -m pip install dataserv-client`, but getting this error:

> Command "python setup.py egg_info" failed with error code 1 in C:\Users\eazyi\AppData\Local\Temp\pip-build-_m2weyl4\RandomIO\

What could be wrong?

**Comment by littleskunk** [comment]
Why don't you use the windows binary? https://github.com/Storj/dataserv-client/releases

**Comment by IgorGanapolsky** [comment]
Because it doesn't work.  It doesn't launch the GUI, but instead presents an error:
![err](https://cloud.githubusercontent.com/assets/201209/13927002/244cf30a-ef65-11e5-994c-208d9a93d87d.png)

**Comment by littleskunk** [comment]
That is not the dataserv-client binary. That error comes from driveshare-gui and I did send you the solution on slack one hour ago. 

I still don't understand what you are doing. Windows driveshare-gui will ignore your dataserv-client pip installation and download the dataserv-client binary. The error message has nothing to do with dataserv-client. Your screenshot looks like a python3 installation. dataserv-client pip installation will not work with python3 at the moment. Try it with python2 and it should work. Remember that has nothing to do with your driveshare-gui problem.

**Comment by IgorGanapolsky** [comment]
What's the difference between the GUI and the client?

**Comment by littleskunk** [comment]
Wrong place for FAQ. Time to close this issue.

Dataserv-client is a command line tool. Driveshare-gui is a gui and runs dataserv-client in the backgroud. Not all dataserv-client options are available for the gui.

**Comment by IgorGanapolsky** [comment]
@littleskunk Why are you disseminating wrong information?  Python 2.7 makes no difference.  See screenshot!!!
![err](https://cloud.githubusercontent.com/assets/201209/13928320/84b87d80-ef6b-11e5-86c8-20670a8d4d3e.png)

**Comment by littleskunk** [comment]
**Windows driveshare-gui will ignore your dataserv-client pip installation and download the dataserv-client binary. The error message has nothing to do with dataserv-client.**
