### ISSUE TITLE
dataserv-client.exe not present

### ISSUE THREAD

**Issue by IgorGanapolsky** [Storj/dataserv-client#209]
I am following instructions here: https://driveshare.org/dataserv.html.  It says there is supposed to be a **dataserv-client.exe** somewhere.  However, it is nowhere to be found.  I keep encountering this error:

> dataserv-client' is not recognized as an internal or external command

Please advise.

**Comment by littleskunk** [comment]
1) Download dataserv-client for windows here: https://github.com/Storj/dataserv-client/releases
2) Go to your download location. Usualy `%userprofile%/Downloads`
3) Extract the downloaded zip file to any location you like. Lets take `C:\`
4) Open the command line (Win+r and enter `cmd`)
5) Execute `cd C:\dataserv-client`
6) Execute `dataserv-client.exe version`
7) You are ready to go. More information you will find here: https://github.com/Storj/dataserv-client/blob/master/README.rst#farmer-quickstart-guide
8) Please use slack for any remaining Question. Github is the wrong place for FAQ.

**Comment by IgorGanapolsky** [comment]
@littleskunk Thanks!  @changetip $1

**Comment by changetip** [comment]
Hi @littleskunk, I've delivered a tip worth 2,386 bits ($1.00) from @IgorGanapolsky.

**[Learn about ChangeTip](https://www.changetip.com/tip-online/github)**
