### ISSUE TITLE
Failed to config dataserv-client in command line

### ISSUE THREAD

**Issue by fm365** [Storj/dataserv-client#212]
build version: dataserv-client-2.1.12.win32.hotfix.zip

error message: 

_D:\App\dataserv-client>dataserv-client.exe config --set_payout_address=13iFGBvwi
dqkybk6coQjzCWpiQ27ox996i
openssl env not found
None
Current configuration.

```
Authentication address: 16L5RGXhJFbPd24xupFXTwAKtKXZqFYwrd
Payout address: 13iFGBvwidqkybk6coQjzCWpiQ27ox996i_
```

**Comment by fm365** [comment]
anybody knows how to fix it ?  
And I am sure I set env variable for "openssl"  through the following command : 

D:\App\dataserv-client>set Path=%Path%;d:\App\GnuWin32\bin

**Comment by fm365** [comment]
verified: 

The message "openssl env not found" can be ignored.

**Comment by littleskunk** [comment]
PYCOIN_NATIVE=openssl is missing ;)

https://github.com/Storj/farmer-gui/issues/191#issuecomment-190755322
