### ISSUE TITLE
No warning on read only volume

### ISSUE THREAD

**Issue by alphaonex86** [Storj/dataserv-client#23]
Hello,
python3.3 dataserv-client --address XXXXXXXXXXXXXXXXXX --max_size 979789414400 --store_path /path/dataserv_client/bin/data/ poll
No warning when the file is on read only for the current user (rw-r--r-- root, current user: driveshare)
http://104.236.104.117/api/online -> show Height: 0
Thanks to fix it.

**Comment by super3** [comment]
Did you use build?

**Comment by alphaonex86** [comment]
No the version 1.1

**Comment by super3** [comment]
Seems like an OS level error. We don't check permissions for folders we are going to write. You have to properly build first, or your height is going to be 0. 

http://driveshare.org/dataserv.html

**Comment by alphaonex86** [comment]
Yes it's OS level error, unable to open in read/write the file. But not show by the software. The build was done by root, then the build is successful. (properly build)
