### ISSUE TITLE
dataserv-client.exe stopped working but didn´t exit to command prompt

### ISSUE THREAD

**Issue by heunland** [Storj/dataserv-client#24]
The dataserv-client.exe just suddenly stopped working for no apparent reason (on windows 7, on external HDD attached to PC). An error window appeared saying "The program stopped to function correctly because of a problem. Windows will close the program and notify if a solution exists." I had to manually click the "close program" button to return to the command prompt in the command window. 
No further info appeared in the command window. It just went back to command prompt. I restarted polling manually and now polling again without problems.

**Comment by super3** [comment]
Thanks for the bug report, but we don't have any much information to reproduce the error and figure out what happened. Let us know if this happens again.
