### ISSUE TITLE
build failed at last time

### ISSUE THREAD

**Issue by alphaonex86** [Storj/dataserv-client#25]
Hello,

At last time the build have failed.
Can you do the server call before start the build? (prevent network failed broke the build). Address not registred bug all the build and it's say after the build.
If reserve if forgot before build do it, if build if forgot before poll do it.

Cheers,

**Comment by super3** [comment]
As per the instructions: http://driveshare.org/dataserv.html you need to register before building. While this will always be the case, the newer version will allow you to simply quickly rerun build if you didn't register.

**Comment by alphaonex86** [comment]
Never trust user input ;) Some user will don't follow the instruction. This work around will save you time by preventing user issue report.
