### ISSUE TITLE
Thread the crypto (cpu) part and HDD write part for build

### ISSUE THREAD

**Issue by alphaonex86** [Storj/dataserv-client#29]
Hello,

The program seam alternate cpu usage and hdd write part. Maybe loop { compute ; write }
Can you thread the compute to transform your serial code into parallel code? And be able to use all cpu core?

Cheers,

**Comment by super3** [comment]
In the future the builder will be highly CPU bound, so no need to make improvements to the write at this time.

**Comment by alphaonex86** [comment]
Some device can be slow but big iSCSI and NAS. My query is too for use thread to use all cpu of the platform
