### ISSUE TITLE
Speed Up Unit Tests

### ISSUE THREAD

**Issue by F483** [Storj/dataserv-client#34]
Tests on travis are taking up to 17min to complete. Faster test would improve development feedback and its likely this can be sped up dramatically with just minimal effort.

**Comment by littleskunk** [comment]
there are 2 Polls with 1 Minutes Timeout. Change it to 2 sec delay and 10 sec Timeout. Unit Test schould be 5 Minutes faster.

**Comment by littleskunk** [comment]
missed one 60 sec poll. now that is fixed as well. at the end the unit test is 7-8 minutes faster. i am not sure if i can speed it up more. can u live with 13 minutes?

is it possible to print out some time information? the unit test is calculating the duration of the installation and the complete unit test but with some more information we could see which test is slow.

last but not least. the tests runs 3 times with different python version. is it possible to run them at the same time on 3 different machines? that way the test would only need 5 minutes. the 3 tests should be indipendent. if needed we can use 3 different public keys.

**Comment by littleskunk** [comment]
Well the information from Travis is wrong. The 3 python test already run paralell. 5 minutes after my checkin Travis reported a 13 minutes test. 

waiting for the pull request accept. after than i will try to add some more duration information.

**Comment by F483** [comment]
Regardless if travis numbers are correct or not, it still takes long to run all the tests.
Your patch was accepted and improved the test speed. I also moved the dependencies to requirements files which lets you build wheels locally and made each test use generated unique addresses so it is no longer needed to have a server spin up for each test.
These things have reduced the edit test loop quiet a bit. I feel there are still many simple but effective improvements to be made, so I am leaving the issue open.
