### ISSUE TITLE
Improve Error Messages for Expected Failure Modes

### ISSUE THREAD

**Issue by F483** [Storj/dataserv-client#35]
Currently if a client cause a common error such as registering an address more then once, they see a stack trace and it is not apparent to them what happened.

I suggest for expected failure modes such as registering an address more then once, the exception should be caught, a simple clear understandable error printed and the program should exit gracefully.

**Comment by super3** [comment]
@F483 Is this still needed?

**Comment by F483** [comment]
I dont think so as dataserv-client may be deprecated soon
