### ISSUE TITLE
readme - version in setup part

### ISSUE THREAD

**Issue by beulemann** [Storj/dataserv-client#37]
$ sudo pip3 install dataserv-client==1.1.0

is this the right version?
or should it be 1.3.0?

**Comment by unsystemizer** [comment]
It depends what are you trying to do.
If you're installing 1.1.0, then that is the right version.

**Comment by super3** [comment]
@beulemann it should be version 1.3.0

**Comment by F483** [comment]
The version should not be specified in the readme (so it gets the latest). I have changed this and it will be fixed in the next release.
