### ISSUE TITLE
Wallet address validation

### ISSUE THREAD

**Issue by NutterzUK** [Storj/dataserv-client#4]
Validation of the wallet address when building, registering and polling commands are used.

**Comment by F483** [comment]
Will make sure all addresses are valid bitcoin addresses.

**Comment by super3** [comment]
@F483 Already built this in: https://github.com/Storj/dataserv/blob/master/dataserv/Validator.py

**Comment by F483** [comment]
I think this code belongs in btctxstore. I will add a validate_address and validate_wif methods if thats ok with you.

**Comment by super3** [comment]
If you can just merge in the existing code into btctxstore that would be great.

**Comment by F483** [comment]
Actually pycoin has it own validation functions which I already use internally, I just need to expose it via the api.

**Comment by F483** [comment]
Has been added implicitly with wallet generation.
