### ISSUE TITLE
Confirm allocated disk space is correct.

### ISSUE THREAD

**Issue by F483** [Storj/dataserv-client#45]
> so I started my build with the following bytes 3298534883328. I wake up this morning to it complaining about disk space and I now see 3.47TB used in my drive. Why did it go so far past 3TB? 

 - brandon 4:26 PM (in 'dev')

**Comment by subwolf** [comment]
Hmmm thats right, 3298534883328 / 1024 / 1024 / 1024 = 3072 or 3 TiB

**Comment by super3** [comment]
Well the next version should fix that. Because we allow users to say GB or TB instead of bytes. Note there is going to be an error of 1 height(128 MB) when building.

**Comment by super3** [comment]
We changed the way that we pass build sizes as of 6f3f6d896e990c78c4057b5ecd89d7f1144f5a4e. When the next update goes out, please verify that your issue is gone. If not then reopen issue.
