### ISSUE TITLE
User setting fake height.

### ISSUE THREAD

**Issue by F483** [Storj/dataserv-client#49]
> @fabe: someone is setting fake height again apparently: 1CounterpartyXXXXXXXXXXXXXXXUWLpVr | Last Seen: 2 second(s) | Height: 999999999999999999 

- heunland 2:35 PM

**Comment by super3** [comment]
Eliminated crazy heights with 3b47bf988c4c17cc1b95ea6c00a9d0e91b07f598 on dataserv, which sets 25 TB max per address. Authentication will fix other height issues, and audits will be the end all.
