### ISSUE TITLE
Registering and building in new client on the same machine disturbs an existing polling client

### ISSUE THREAD

**Issue by NutterzUK** [Storj/dataserv-client#5]
I had a 2TB store on E:/Storj which was polling.

Registered a new address in another CMD prompt on windows.
Starting a build on the new address, specifying a different store directory (G:/storj).

This then stopped the first client which was polling from being picked up on the server at : http://104.236.104.117/api/online
Although it continued to ping.

To fix it I had to start the client again.

Using windows 10.

Perhaps every command should require a build path and an address rather than remembering them somehow (Not sure how that works, but I am convinced the issue is it there is some shared data between the two running clients somewhere).

**Comment by super3** [comment]
So it froze the 1st client, and then worked after you restarted? Can you copy paste all the commands you used?

**Comment by NutterzUK** [comment]
Closing this issue - It doesn't seem to happen anymore, my apologies.
