### ISSUE TITLE
Sign auto updates.

### ISSUE THREAD

**Issue by NutterzUK** [Storj/dataserv-client#53]
From the chat:

nutterzuk [4:00 PM] 
Just a quick question - how secure is the auto update?

nutterzuk [4:00 PM]
There is absolutely no risk someone manages to get everyones clients downloading a malicious update?

nutterzuk [4:03 PM]
Using some kinda certificate or signing perhaps?

shawn [4:04 PM] 
yeah a multisig that we control needs to be added

nutterzuk [4:04 PM] 
As in that's done already and needs to be used to sign an update?

nutterzuk [4:04 PM]
Or that needs to be added as in yeah, it's not implemented yet

shawn [4:04 PM] 
make an issue for it

shawn [4:04 PM]
i don't think thats implemented

**Comment by F483** [comment]
Auto update checks for releases located at https://driveshare.org/bin/dataserv-client 
To compromise clients you would have to place an update in that location.

As far as I know esky (which we use for auto updates) does not support signature verification.
It may be that we can add signature verification ourselves, but that needs to be researched first.

**Comment by super3** [comment]
We can use simple Bitcoin signature authentication. Create a multisig address, and sign the hash of the binary.

**Comment by F483** [comment]
Yes we can sign the hash of the binary and verify it easily. The question is how easy it is to integrate into esky. This is something I will look into for the next release.

**Comment by NutterzUK** [comment]
Just to add some thoughts on this (Although i'm not a storj dev):

- The public addresses would need to be built into the client itself so it knows what to check after downloading an update, I assume it would check the sig before updating rather than updating then checking (Sounds like a stupid question but i'd rather ask to make sure).

- I'm don't think the only way to attack this would  be for a client to place an update in that location (although that's one way). I think it would be possible to attack a public network or modify router settings similar to how you can do in your hosts file to redirect requests that should be going to that server to elsewhere, without the client knowing. E.g http://superuser.com/questions/402194/can-a-router-map-a-url-to-a-local-ip

Perhaps attacking the DNS server too. It sounds extreme, but people are likely to have BTC wallets on the machines running this so it's not actually that unlikely that people will go to lengths to attack it and gain access.

I have no idea how esky works, but as an outsider I would assume the process should be:
- Check for updates, if one exists, download it, do not execute it yet.
- Check the update is from where it should be by using bitcoin signature authentication.
- If it is, install it.
- If it isn't... log it and delete the downloaded update. Perhaps alert the user so they know someone is up to something naughty (or the file was corrupted).

**Comment by super3** [comment]
Yup your esky process makes senses. Lets figure out how to get that done.

Shawn

On Mon, Aug 24, 2015 at 2:01 PM, Stephen Nutbrown <notifications@github.com>
wrote:

> Just to add some thoughts on this (Although i'm not a storj dev):
>
>    -
>
>    The public addresses would need to be built into the client itself so
>    it knows what to check after downloading an update, I assume it would check
>    the sig before updating rather than updating then checking (Sounds like a
>    stupid question but i'd rather ask to make sure).
>    -
>
>    I'm don't think the only way to attack this would be for a client to
>    place an update in that location (although that's one way). I think it
>    would be possible to attack a public network or modify router settings
>    similar to how you can do in your hosts file to redirect requests that
>    should be going to that server to elsewhere, without the client knowing.
>    E.g
>    http://superuser.com/questions/402194/can-a-router-map-a-url-to-a-local-ip
>
> Perhaps attacking the DNS server too. It sounds extreme, but people are
> likely to have BTC wallets on the machines running this so it's not
> actually that unlikely that people will go to lengths to attack it and gain
> access.
>
> I have no idea how esky works, but as an outsider I would assume the
> process should be:
>
>    - Check for updates, if one exists, download it, do not execute it yet.
>    - Check the update is from where it should be by using bitcoin
>    signature authentication.
>    - If it is, install it.
>    - If it isn't... log it and delete the downloaded update. Perhaps
>    alert the user so they know someone is up to something naughty (or the file
>    was corrupted).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Storj/dataserv-client/issues/53#issuecomment-134319007>
> .
>



-- 
Shawn Wilkinson
Lead Developer and Founder | storj.io
me@super3.org | super3.org

**Comment by super3** [comment]
I'm suddenly uncomfortable with auto-update function. Vectors of attack include the website, and esky. Disabling it all together, until the routes are secure.

**Comment by F483** [comment]
Auto update removed due to security issues.
