### ISSUE TITLE
dataserv-client 2.0.0 [WinError 10061]

### ISSUE THREAD

**Issue by luishmendes** [Storj/dataserv-client#56]
ERROR UPDATING DATASERV-CLIENT: urlopen error [WinError 10061] Nenhuma ligação pôde ser feita porque o computador de destino as recusou ativamente

I'm getting this error. What is wrong ?

Thanks

**Comment by super3** [comment]
We have not official released 2.0, and it will not work at this time. Use version 1.3

**Comment by luishmendes** [comment]
Thanks
