### ISSUE TITLE
upgrade does not work

### ISSUE THREAD

**Issue by beulemann** [Storj/dataserv-client#57]
sudo pip3 install dataserv-client --upgrade
Downloading/unpacking dataserv-client from https://pypi.python.org/packages/source/d/dataserv-client/dataserv-client-2.0.0.tar.gz#md5=b75fc5880377d255de7de8462f7b1693
  Downloading dataserv-client-2.0.0.tar.gz
  Running setup.py (path:/tmp/pip-build-bpaqoypm/dataserv-client/setup.py) egg_info for package dataserv-client
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-bpaqoypm/dataserv-client/setup.py", line 35, in <module>
        install_requires=open("requirements.txt").readlines(),
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-bpaqoypm/dataserv-client/setup.py", line 35, in <module>

    install_requires=open("requirements.txt").readlines(),

FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-bpaqoypm/dataserv-client
Storing debug log for failure in /home/beulemann/.pip/pip.log

**Comment by beulemann** [comment]
where do i get the requirements.txt from, and where to place it?

**Comment by super3** [comment]
Upgrade is premature. We are still fixing bugs.
