### ISSUE TITLE
Master Secret Reset

### ISSUE THREAD

**Issue by super3** [Storj/dataserv-client#58]
Master secret resets on rerun.
```{"version": "2.0.0", "master_secret": null, "payout_address": "1JdEaubcM36ufmT64drdVsGu5SN65A3Z1L"}```

**Comment by F483** [comment]
I cannot reproduce the error on my linux client or on the built windows release. From a previous post for yours, I have reason to believe it may be specific to your setup.

    C:\Python34\python.exe C:/Users/super3/Code/dataserv-client/dataserv_client/bin/dataserv-client --set_payout_address 1JdEaubcM36ufmT64drdVsGu5SN65A3Z1L show_config
    {
      "payout_address": "1JdEaubcM36ufmT64drdVsGu5SN65A3Z1L",
      "version": "2.0.0",
      "master_secret": null
    }

I see you run the script directly, this expects dataserv-client to be installed in the python libs via `python setup.py install` is that the case?

**Comment by F483** [comment]
Just managed to reproduce it as well. Looking into what it could be.

**Comment by F483** [comment]
Fixed
