### ISSUE TITLE
Input of max_size - support for other measurements

### ISSUE THREAD

**Issue by NutterzUK** [Storj/dataserv-client#6]
Eg an argument of 2TB rather than however many bytes, perhaps support for b,kb,mb,gb,tb.

Probably low priority as this will be fixed with a GUI, but it would be good in case anyone else is creating third party GUIs of any sort.

**Comment by F483** [comment]
To many standards or the lack thereof ... is one kb 1024 bytes or 1000 bytes ?

I suggest we use postfixes in line with the way the unix 'dd' program and most unix systems expect, to avoid confusion.

1K = 1024^1 bytes
1KB = 1000^1 bytes
1M = 1024^2 bytes
1MB = 1000^2 bytes
1G = 1024^3 bytes
1GB = 1000^3 bytes
1T = 1024^4 bytes
1TB = 1000^4 bytes
1P = 1024^5 bytes
1PB = 1000^5 bytes

**Comment by super3** [comment]
Sounds reasonable to me. Got for it.

**Comment by F483** [comment]
Syntax added to max_size option.
