### ISSUE TITLE
buid skips corrupted files

### ISSUE THREAD

**Issue by littleskunk** [Storj/dataserv-client#61]
first build stoped with a error or get killed by the user. it writes a corrupted file that is < 128 MB.

build started again and skips files identified by filename. it skips corrupted files as well.

**Comment by F483** [comment]
Will always rebuild last block in case its corrupt. https://github.com/Storj/dataserv-client/commit/61f1e9ac6e0128d76c9eb68d01091f37dca116fd

**Comment by littleskunk** [comment]
i had 4 corrupted files cause of 4 stoped builds. with your change only one of the corrupted file would be generated again.

**Comment by F483** [comment]
Yes that is correct. It fixed the inherent problem and prevents it in the future, but if you already have multiple corrupt block it is advised you rebuild.
