### ISSUE TITLE
Need last verification test for winners after making result shapshot to verify its height

### ISSUE THREAD

**Issue by Karasur** [Storj/dataserv-client#62]
There is strange winner 1Hh6A1v4ZBKs8vLywm4FiGRPpvPfRcbZqS,  it appears before snapshot at the right time with more than 10000 height (6-10 hours after dissapearing from active list)!
It will be fair to check and confirm winners result with some verification tool, that the winner have the exact and valid files on his storage.

**Comment by Honorificabilitudinitatibus** [comment]
And I want to know how to check the deterministic random files that each users hold.
Will server(s) make a series of file seeds, make a few randomly selected files, and request a few bytes in these files?

Then malcious users can do the same thing without making whole files, right?

**Comment by littleskunk** [comment]
With a fast cpu and the better seed generation from the new version it is possible to pass the verification faster than with real files.

**Comment by lockthenlock** [comment]
ok let say those can happen, but i dont think all top 10 can do, and have enough equipment/skill, to do so. beside if the verification tool is closed-sources, i dont think they can cheat.

**Comment by Karasur** [comment]
Someone may change client and build parts of seeds with more than one cpu at the same time, and later unite seeds in folder.
Like the winner i think, its impossible to build 10000 height with 1 cpu for 6-10 hours.
When you relaunch build process it recheck you file from 0 height and you should wait 1-3 sec per height to rise your height max.
Or just dont count height as a big value to calculate reward.
As shawn mention before, half reward will be contribute for running address, meaning participate users, half will scaled by height seems fair.

**Comment by lockthenlock** [comment]
@Karasur i actually port the python code to do so, but remember that even that: 1) building seed is sequenced process, mean seed x hash is belong to its previous seed, so basically it cannot be parallel but it will quicker for better cpu 2) final seed will write to hard disk, so it depend on IOPS of disk not cpu any more.

**Comment by Honorificabilitudinitatibus** [comment]
I don't know about programs and future plans very much , but in my understanding,

build:
1. seed=sha256(address)
2. make 128MB shard from seed
3. seed=sha256(seed)
4. goto 1

audit(?)
1.  select 1 file randomly (assume number N of files)
2.  seed=sha256(address);for i<N seed=sha256(seed)
3. make a 128MB shard from seed
4. select and request a few bytes to the user

so fast cpus are not needed(?), I guess.
Anyway unless server makes all and whole files, I guess user can do the same thing as server does 
to cheat.

and server is(and should be) also opened (right?)
https://github.com/Storj/dataserv

**Comment by littleskunk** [comment]
@lockthenlock
If the verification is closed-sources i will not start it. we are dealing with bitcoin addr....

but anyway. my nas is to slow for the verification. it will need days again. in the same time i can install that storage into my pc. with the seed generation of the new version it can generate the files faster than my nas could verifiy. that way it is possible to use 25TB for different addr.

@Honorificabilitudinitatibus
i have the code ready for fake audit. we should use the test for testing and not for cheating or anti cheating. we cant stop the cheater. but we can help the devs testing everything they planed.

**Comment by Honorificabilitudinitatibus** [comment]
@littleskunk
agree with you :)

**Comment by super3** [comment]
See https://github.com/storj/partialhash for the audit library.

**Comment by super3** [comment]
@Honorificabilitudinitatibus Fixing bugs right now. Pretty stable right now. Adding uptime and audits next. This issues will be handled in #137
