### ISSUE TITLE
Improve query performance by using urllib3

### ISSUE THREAD

**Issue by bsom** [Storj/dataserv-client#63]
URLLib is slow.  It will open and close a port to the web server for every http transaction.  URLLib3 has the ability to leave a port open.  If the server can handle the load, leaving the port open for new http transactions speeds things up considerably.

Reassessing seeds of files that have already been built is painfully slow and I think it is because of all of the overhead of opening and closing the connection to the server.  URLLib3 *could possibly* speed that up considerably at the cost of server load.

**Comment by F483** [comment]
Thank you bsom will look into using urllib3!

**Comment by bsom** [comment]
There is also a wrapper for URLLib called Requests, that makes life even easier.  No more messy code.  Simple and elegant.  http://docs.python-requests.org/en/latest/

**Comment by F483** [comment]
Again thank you very much @bsom ! Will add it asap.

**Comment by super3** [comment]
Currently using a node for testing for Test Group B. We intend to abandon this in the future as we move to more decentralized messaging.
