### ISSUE TITLE
Cannot register address

### ISSUE THREAD

**Issue by enkumber** [Storj/dataserv-client#65]
When I try to register: 
dataserv-client config --set_payout_address=BTCADDRESS
i get 
error: argument <command>: invalid choice: 'config' (choose from 'version', 'register', 'ping', 'poll', 'build')

**Comment by F483** [comment]
What version are you using? The config command was added in 2.0.2, can you paste your output for `dataserv-client version`

**Comment by enkumber** [comment]
i have 1.3.0 and I got help from slack channel. thanks anyway
