### ISSUE TITLE
height stuck at 4, no error

### ISSUE THREAD

**Issue by anwfr** [Storj/dataserv-client#66]
Hi,
I built 750gb share and dataserv-client is running fine on my linux server, pinging and appearing in http://104.236.104.117/api/online for a week.
But the "height" reported is not increasing and keeps stuck at "4". Is it normal or does this mean I'm not storing anything?
Thanks

**Comment by super3** [comment]
You need to rebuild. Run the build command again.

**Comment by anwfr** [comment]
ok, but shouldn't it display a warning or something?
If I didn't check on the API there is no mean to know a rebuild is required. Client seems running normally.
