### ISSUE TITLE
pip3 requirements.txt missing

### ISSUE THREAD

**Issue by homsch** [Storj/dataserv-client#70]
command:
sudo pip3.4 install dataserv-client

error:
File "/tmp/pip_build_root/dataserv-client/setup.py", line 35, in <module> install_requires=open("requirements.txt").readlines(),
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

solution:
include requirements.txt into dataserv-client-2.0.0.tar.gz

system:
- raspberry pi2 
- python 3.4 self compiled

**Comment by unsystemizer** [comment]
https://github.com/Storj/dataserv-client/blob/master/requirements.txt

The file is there.

**Comment by F483** [comment]
That is odd, did you maybe call the command from another directory?

**Comment by homsch** [comment]
I`m aware of requirements.txt is in the git repository.
But I would like install with pip, like described  on the git Storj/dataserv-client
startpage (Ubuntu Linux section)

the pip command uses the dataserv-client-2.0.0.tar.gz located on
https://pypi.python.org/pypi/dataserv-client/2.0.0

The fault is:
dataserv-client-2.0.0.tar.gz doesn´t contain the file requirements.txt (you can see it when you click on Download on https://pypi.python.org/pypi/dataserv-client/2.0.0).
So pip can`t install correctly.

I wonder that other people doesn`t have the same problem?


command:
pi@streamer ~/entwicklung/Python-3.4.0 $ sudo pip3.4 install dataserv-client

complete Console output:
Downloading/unpacking dataserv-client
  Downloading dataserv-client-2.0.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/dataserv-client/setup.py) egg_info for package dataserv-client
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/dataserv-client/setup.py", line 35, in <module>
        install_requires=open("requirements.txt").readlines(),
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/dataserv-client/setup.py", line 35, in 
  install_requires=open("requirements.txt").readlines(),

FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

----------------------------------------
Cleaning up...

**Comment by unsystemizer** [comment]
Just download the file

**Comment by meecoder** [comment]
Try this: sudo pip install git+https://github.com/Storj/dataserv-client

**Comment by homsch** [comment]
Thanks meecoder it works with pip. For me.
Unfortunately it´s a workaround, It would be better
when it works with the command which is described on the git startpage:

sudo pip3 install dataserv-client

**Comment by F483** [comment]
> dataserv-client-2.0.0.tar.gz doesn´t contain the file requirements.txt

This is a bug! Thank you for the report, I will fix it.

**Comment by F483** [comment]
Fixed in https://github.com/Storj/dataserv-client/commit/dc6fbc6031e6498d9930e1ae6e4b7b8945cd076b
