### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by luishmendes** [Storj/dataserv-client#72]
I'm getting this error during build after a few hours.
I have to always go back to the beginning.

![error](https://cloud.githubusercontent.com/assets/13944410/9553904/0b3748f4-4dba-11e5-8520-52b2a37d6d52.jpg)

SO: Windows 10 X64
Thanks

**Comment by F483** [comment]
This seems to be on the server side, I will check the logs and fix it. Thank you for reporting the error.
