### ISSUE TITLE
Out of Memory building with version 2.0.3

### ISSUE THREAD

**Issue by littleskunk** [Storj/dataserv-client#73]
Kernel kills the process with out of memory warning. My NAS has 2GB RAM. I gues the reason is the new seed generation.

**Comment by F483** [comment]
Good to know. Can you give the exact error message and the command you used?

**Comment by littleskunk** [comment]
dataserv-client --url=http://status.driveshare.org:5000 --max_size=1PB --store_path=[...] --debug build &

1PB is to much. changed it to 15TB and it works. I will run on a low disk space error anyway.

**Comment by F483** [comment]
It would still be nice to know what the exact error message was if possible, so we can maybe have it exit more gracefully.

**Comment by littleskunk** [comment]
I get only the messages "killed" and in the webfrontend of my nas the notification "[Kernel] Out-of-Memory. Kill process <Number>(dataserv-client)
