### ISSUE TITLE
Height 1 reported after registering, building then polling.

### ISSUE THREAD

**Issue by NutterzUK** [Storj/dataserv-client#74]
C:\Users\steve\Desktop\ds2>dataserv-client.exe --url http://status.Driveshare.org:5000 --max_size 2T --store_path G:\storj build

C:\Users\steve\Desktop\ds2>dataserv-client --store_path G:\storj --url http://status.driveshare.org:5000 poll

Shows height 1 after build.

**Comment by F483** [comment]
This is a resume from an old build or a fresh build?
Did you set the payout address before registering with the new client?

**Comment by F483** [comment]
Cannot confirm with latests build. See log below.

$ rm -rf ~/.storj
$ dataserv-client --debug --url=http://127.0.0.1:5000 farm
Query: http://127.0.0.1:5000/api/address
Query: http://127.0.0.1:5000/api/register/1CWxMsRu8RpB143M7qgsjegHEEtCquYZiN/1CWxMsRu8RpB143M7qgsjegHEEtCquYZiN
Registered on server 'http://127.0.0.1:5000'.
Starting build
Resuming from height 1
Saving seed 0b953a01034fe13cb4437ea56ea0f0f2dd1a54394f6474c691da7b5dff9cef2d with SHA-256 hash e07ff1e0e4a8abadc3c3c3da1b6773176de5a1afc43de99958daab44858f39fa.
Query: http://127.0.0.1:5000/api/height/1CWxMsRu8RpB143M7qgsjegHEEtCquYZiN/1
Current height at 1.
Saving seed f7075bd0747245a2c495cae10acd6697076125bf1872b06a776db689c1eed376 with SHA-256 hash a4fb570dfb34c28417d880856723c7b13465010a9bc054f2637defd6d9934b8c.
Saving seed acda6d48565239068fe78f966417523ed20ec42f7df72ca1160282ba66dff4fa with SHA-256 hash bf215001ac3ff48747424ef4c10e937b27e388ea177ef02e364180e3c0d92019.
Saving seed 472f782068acf3bfe6b8d8e2ce5fd1c43da7c2c1a9f7d2c894e64adcbdc8dd74 with SHA-256 hash 08ed2729c5a18a95bbffe59a265ef911164a22de754ef872ee64116bba748a66.
Saving seed f63ce7bb5954c0b03ad92b776c956f5efb76918de73d63b7d3675d55de725c5e with SHA-256 hash b59f8686b326522e147517cd76b08c534a4c1ab56ea97c215f7e9d0d18335583.
Saving seed a9d69307ef248de392225f0877df07eb06f1ade2ce77a0676f6d6ecf94f8846e with SHA-256 hash 235739005b2c3050a65627c60d1c61b263e1800b9937ad9b53a4e7bd17d179c2.
Saving seed 9473927e8297706ab2708b6f1998c45eb2871c3a3ba1eb0ac00c2e66a019f1a0 with SHA-256 hash 78b02c9cefbf497bd3867ac112d23403a1d0bc51b82a350c102d08d133b221db.
Saving seed 8391610e2d06915acd79729f96569cc32dfab1ae229e531951fba4de433c03d8 with SHA-256 hash baa3a6734eca0181b3ec626f60525245b20f32df0c24074ed2e9222ac1099798.
Query: http://127.0.0.1:5000/api/height/1CWxMsRu8RpB143M7qgsjegHEEtCquYZiN/8
Current height at 8.
Build finished
Pinging server 'http://127.0.0.1:5000' at 2015-08-30 17:57:20.
Query: http://127.0.0.1:5000/api/ping/1CWxMsRu8RpB143M7qgsjegHEEtCquYZiN

$ dataserv-client --debug --url=http://127.0.0.1:5000 farm
Query: http://127.0.0.1:5000/api/address
Query: http://127.0.0.1:5000/api/register/1CWxMsRu8RpB143M7qgsjegHEEtCquYZiN/1CWxMsRu8RpB143M7qgsjegHEEtCquYZiN
Error: HTTPError()
Starting build
Resuming from height 8
Saving seed 8391610e2d06915acd79729f96569cc32dfab1ae229e531951fba4de433c03d8 with SHA-256 hash baa3a6734eca0181b3ec626f60525245b20f32df0c24074ed2e9222ac1099798.
Query: http://127.0.0.1:5000/api/height/1CWxMsRu8RpB143M7qgsjegHEEtCquYZiN/8
Current height at 8.
Build finished
Pinging server 'http://127.0.0.1:5000' at 2015-08-30 17:57:44.
Query: http://127.0.0.1:5000/api/ping/1CWxMsRu8RpB143M7qgsjegHEEtCquYZiN
