### ISSUE TITLE
Unable to set --config_path

### ISSUE THREAD

**Issue by dlmac** [Storj/dataserv-client#75]
I have two builds on same machine, 1st build is up and running. unable to set --config_path for 2nd build to keep from conflicting with 1st build.

Commands for 2nd build:
1. dataserv-client --config_path "E:\storj\config.json" config
2. config is generated (with the same wallet as first build)
3. dataserv-client config --set_payout_address=1FATEJQaSKhxvo9BuXgGmYo6MQD5Jhfsti --config_path "E:\storj\config.json"
I get; error: unrecognized arguments: --config_path E:\storj\config.json

I am unable to keep the 2nd config path set for other commands. If I run without --config_path I overwrite 1st config.

**Comment by KLIM8D** [comment]
I think the right command is: `dataserv-client --config_path=E:\storj\config.json`

You might have to escape some of the characters. Since I'm not using Windows, I'm not sure if it matters, but you can try if above doens't work.
`dataserv-client --config_path=E\:\\storj\\config.json`

**Comment by F483** [comment]
both --config_path PATH and --config_path=PATH should work, but under windows you make have to put the path in quotes and escape the backslashes and spaces.

**Comment by dlmac** [comment]
It was the command order. I can't do dataserv-client --config_path “E:\storj\config.json” --set_payout_address=1FATEJQaSKhxvo9BuXgGmYo6MQD5Jhfsti  config  

But this works:
dataserv-client --config_path “E:\storj\config.json” config --set_payout_address=1FATEJQaSKhxvo9BuXgGmYo6MQD5Jhfsti  

In windows you do not have to escape, but I did add quotes.

**Comment by F483** [comment]
Yes there is a difference between global programme arguments and command arguments.

See the readme for more information https://github.com/Storj/dataserv-client#argument-ordering

**Comment by KLIM8D** [comment]
Either this is a bug then or the readme is wrong. As you can see in the readme you linked, both of the optional parameters should be given before the command, `config`, and not afterwards like the example from @dlmac which worked.

**Comment by F483** [comment]
The example from @dlmac is correct and in line with the readme.

Maybe this will make things more clear @KLIM8D.

Below is this command broken down into its components.`dataserv-client --config_path “E:\storj\config.json” config --set_payout_address=1FATEJQaSKhxvo9BuXgGmYo6MQD5Jhfsti`


    dataserv-client                                 # the executable program itself
    --config_path “E:\storj\config.json”   # a program argument, at it is needed by everything
    config                                               # the comand to edit/display the config
    --set_payout_address=1FA...fsti      # a command argument (in this case changing the payout address)

**Comment by KLIM8D** [comment]
Yes according to the argument-ordering you're right, but what I meant was what is displayed by the help command.
> usage: dataserv-client [-h] [--url URL] [--max_size MAX_SIZE]
>                       [--store_path STORE_PATH] [--config_path CONFIG_PATH]
>                       [--debug] [--set_wallet SET_WALLET]
>                       [--set_payout_address SET_PAYOUT_ADDRESS]
>                       <command> ...

> commands:
> <command>
>     ....
>    config              Edit and display config.

According to this all parameters should be given before the command, also `config_path` and `set_payout_address`
