### ISSUE TITLE
MINOR: Add variable to each 'ping' polling debug message

### ISSUE THREAD

**Issue by bsom** [Storj/dataserv-client#76]
It is difficult to tell if polling is still running when every 'ping' message looks the same.  I can't tell if more messages are being generated and scrolling up the window or if poll is frozen.  Perhaps preface each debug message with the time and date?  Minor point, but helpful to me.

**Comment by F483** [comment]
Thank you for the feedback! I will add a time stamp to the output.

**Comment by F483** [comment]
Fixed, see https://github.com/Storj/dataserv-client/commit/7eba725d47a6511f9e191e78718a4eb4c3221a62
