### ISSUE TITLE
2.0.3: height updating slowly (>10 min interval) while build progressing correctly

### ISSUE THREAD

**Issue by unsystemizer** [Storj/dataserv-client#78]
* I start build (it resumed from v1.3.0, say height 100)
* Online I see my height at 110, but then the counter stops incrementing
* I restart the client, it tells me "resuming from height 120" (I tried this twice, it always resumes from a higher height and I can see shards are being created)
* http://status.driveshare.org:5000/api/online still says my height is 110

**Comment by unsystemizer** [comment]
* I deleted all shards made since v2 and restarted build
* After 10 mins, I could see my height increasing from v1.3 height, but then again it got stuck. Locally shards are being added. Maybe it's a matter of waiting long enough for the server to reflect gathered information

**Comment by F483** [comment]
Thank you for the report, I will look into it asap.

**Comment by unsystemizer** [comment]
This isn't mine address, but as an example - I CTRL+F and search for "minutes" and see that 9-10 is not uncommon. 
![image](https://cloud.githubusercontent.com/assets/13134193/9561189/01da2e2a-4e6e-11e5-8e73-a7b0463b3cad.png)

**Comment by unsystemizer** [comment]
Here's why I think it works:
* Updates done in 25 shard increments
* A slow system (such as mine) builds @5 MB/s (even less)
* 25 * 128 MB divided by 5MB/s = 13+ minutes

I'm not sure if this still qualifies as a bug. Maybe it would be sufficient to document this behavior (if I'm right in my speculation).

**Comment by F483** [comment]
You can increase the update interval if you with with `dataserv-client build --set_height_interval=5` That will update every 5 shards instead of the default 25.

**Comment by unsystemizer** [comment]
Thanks. As far as I'm concerned this can be closed, but in case you want to document this somewhere or something like that, I'll leave it open. You can close it at your convenience
