### ISSUE TITLE
Last height not send to the server

### ISSUE THREAD

**Issue by littleskunk** [Storj/dataserv-client#82]
i am building with --set_height_interval=1000000. works perfect even if the server is offline. it should send only the last height to the server but there is a bug in the code.

last = (int(self.max_size / common.SHARD_SIZE) + 1) == cur_height

last is max height + 1 and that will never happen cause build it will stop at max height

**Comment by littleskunk** [comment]
change the local code to last = (int(self.max_size / common.SHARD_SIZE)) == cur_height and that worked. pull request for master and or develop?

**Comment by nrenich** [comment]
I also observed that during the upgrade from 1.3 to 2.03 while already having a finished a 10TB build that it immediately finishes. It will start to poll, but registers a height of 0 on the http://104.236.104.117:5000/api/online site. After I removed approximately 30 shards it rebuilt and adjusted the height and reported it, but in my case it was 81900 when I really have 81920 shards in the build location.

**Comment by linuxman21** [comment]
I actually set the height to report on every 10 so i would not fall off the api stats during the build.

**Comment by F483** [comment]
Thank you very much for the fix! I merged it into develop and it will be in the next release.

**Comment by littleskunk** [comment]
as long as you wait for the bugfix in the next version you may use a workaround.

build with any height_interval you like. default is 25

at the end try this to send your last height to the server.
dataserv-client --url=http://status.driveshare.org:5000 --max_size=1TB --store_path=C:\Storj\ build --set_height_interval=1
