### ISSUE TITLE
Friendly size vs. explicit size on --max_size variable.

### ISSUE THREAD

**Issue by nrenich** [Storj/dataserv-client#85]
I observed that using "--max_size 10995116277760" I would generate 81920 shards, 10TB. I arrived at that byte number using the conversion site: http://www.convertunits.com/from/TB/to/byte
When switching on the command line to "--max_size 10TB" it would report to use a max height of 74505. 
```
C:\dataserv-client>dataserv-client.exe --debug --store_path D:\Storj\Store_1_10TB --max_size 10TB --
url=http://status.driveshare.org:5000 build
Resuming from height 74505
```
Also, it does not appear that you can use decimal places, for example if you selected "--max_size 10.1TB" it will crash with the following:
```
C:\dataserv-client>dataserv-client.exe --debug --store_path D:\Storj\Store_1_10TB --max_size 10.1TB
--url=http://status.driveshare.org:5000 build
Traceback (most recent call last):
  File "dataserv-client", line 10, in <module>
  File "E:\dataserv-client\dataserv_client\cli.py", line 151, in main
  File "E:\dataserv-client\dataserv_client\api.py", line 33, in __init__
  File "E:\dataserv-client\dataserv_client\deserialize.py", line 34, in byte_count
  File "E:\dataserv-client\dataserv_client\deserialize.py", line 14, in _get_byte_count
ValueError: invalid literal for int() with base 10: '10.1'
```
The later may be more of a feature request as it could be quite helpful to easily expand your build on the remaining space of a physical volume.

**Comment by littleskunk** [comment]
Try it with 10T and not 10TB

**Comment by nrenich** [comment]
Thanks @littleskunk that did fix the 81920 reporting properly at the client, but not on the status site. I still would like decimal support as a feature on a future build if possible.

**Comment by littleskunk** [comment]
agree with that. decimal support would be nice.

**Comment by F483** [comment]
Decimal would be nice but not or our radar at the moment, just use the next smaller unit.

# optional max_size syntax
--max_size=1K  # 1024^1 bytes
--max_size=1KB # 1000^1 bytes
--max_size=1M  # 1024^2 bytes
--max_size=1MB # 1000^2 bytes
--max_size=1G  # 1024^3 bytes
--max_size=1GB # 1000^3 bytes
--max_size=1T  # 1024^4 bytes
--max_size=1TB # 1000^4 bytes
--max_size=1P  # 1024^5 bytes
--max_size=1PB # 1000^5 bytes
