### ISSUE TITLE
client cannot self recover after server downtime

### ISSUE THREAD

**Issue by unsystemizer** [Storj/dataserv-client#94]
dataserv-client 2.0.3 remains stuck after server restart and requires a restart.
It probably should be able to resume if it can contact the server again.

**Comment by F483** [comment]
Cannot confirm with latest Linux client.

Windows client still to be confirmed/denied.

**Comment by unsystemizer** [comment]
I encountered the problem on Raspbian, and I think bronan (Slack) also said he had to restart his client (I'm not sure what OS it is).

**Comment by F483** [comment]
Also can confirm this myself, https://github.com/Storj/dataserv-client/issues/63 may be a fix.

**Comment by littleskunk** [comment]
Retest with new version ok on windows and linux. 

@unsystemizer close the bug?
